[build]
  command = "yarn install --ignore-engines && yarn build"
  publish = "dist"

# Optional: specify Node version if needed
[[plugins]]
  package = "@netlify/plugin-node"
  [plugins.inputs]
    node_version = "18"
